### PR TITLE
Fix nfs when control===login

### PR DESCRIPTION
**Pull request by jovial**
The role was trying to mount the share from the same server. Systemd detected
this loop and refused to start the nfs server.

This makes it easier to construct an inventory with a shared control/login node.

### CODE REVIEW

**Comment by sjpb** [comment]
Hmm, I'm not sure this smells right to me TBH, seems to leak info about slurm groups into the nfs setup. Following what we've done elsewhere, shouldn't we just have an nfs_client group and an nfs_server group and set them appropriately? Then actually the hosts for this role could just be both those groups.

Might have to think how would this work for multiple NFS configs though, which might not all have the same client/server setups I guess? I.e. a host can be both client and server at the same time, just not for the same share. (most likely case: entire cluster is client for e.g. "external" Isilon , plus login exports some directory to computes)

**Comment by jovial** [comment]
> Hmm, I'm not sure this smells right to me TBH, seems to leak info about slurm groups into the nfs setup. Following what we've done elsewhere, shouldn't we just have an nfs_client group and an nfs_server group and set them appropriately? Then actually the hosts for this role could just be both those groups.
> 
> Might have to think how would this work for multiple NFS configs though, which might not all have the same client/server setups I guess? I.e. a host can be both client and server at the same time, just not for the same share. (most likely case: entire cluster is client for e.g. "external" Isilon , plus login exports some directory to computes)

Yeah, like you say, not sure how groups would work with multiple shares. This change concerns the `/mnt/nfs` share only. Maybe the logic could be simplified to: `inventory_hostname in groups['cluster'] and inventory_hostname not in groups['control']`.

**Comment by jovial** [comment]
Could also change the role to not mount the share on the server from where it is exported.

**Comment by sjpb** [comment]
> Could also change the role to not mount the share on the server from where it is exported.

I think there are actually some use-cases for that, although whether it's the best idea/something this role needs to support is a fair point.

**Comment by sjpb** [comment]
> The other issue with using groups is that you most likely need to use a constructed inventory to exclude the server, as, for example:
> 
> ```
> [nfs_server:children]
> control
> [nfs_clients:children]
> cluster
> ```
> 
> also includes the server as the client.

With this server/clients groups approach, I was thinking the default would just be:
```
[nfs_server:children]
control
[nfs_clients:children]
compute
login
```

but you're right that you'd have to delete login if that's combined with control

**Comment by sjpb** [comment]
Current fix looks sensible for default case with current groups given that needs to handle both separate and combined login/control groups

**Review by sjpb — APPROVED** [review]
Current fix looks sensible for default case with current groups given that needs to handle both separate and combined login/control groups

**Pull request merged**
