### PR TITLE
Remove locked memory limits on compute nodes

### PR DESCRIPTION
**Pull request by sjpb**
Fixes [slurm role issue #86](https://github.com/stackhpc/ansible-role-openhpc/issues/86)

### CODE REVIEW

**Comment by sjpb** [comment]
Actually this isn't quite right: it should change compute and job submission nodes. The current `"'control' not in group_names"` logic works for separate control and login nodes but not for the combined case.

**Comment by sjpb** [comment]
Document that we only support separate login nodes, not combined login/control.

**Comment by sjpb** [comment]
Added comment to #13 for this.

**Comment by sjpb** [comment]
Note that we could just use the compute,login group then for this action and remove logic.

**Review by jovial — APPROVED** [review]

**Pull request merged**
